# Generated by Django 2.2.24 on 2024-01-11 10:57

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20240111_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=12, region='RU', verbose_name='Нормализованный номер владельца'),
        ),
    ]
