# Generated by Django 2.2.24 on 2024-01-11 17:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20240111_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Own',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200, verbose_name='ФИО владельца')),
                ('owners_phonenumber', models.CharField(max_length=20, verbose_name='Номер владельца')),
                ('owner_pure_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=12, null=True, region='RU', verbose_name='Нормализованный номер владельца')),
                ('flat', models.ManyToManyField(blank=True, to='property.Flat', verbose_name='Квартиры в собственности')),
            ],
        ),
    ]
