# Generated by Django 2.2.24 on 2024-01-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_own'),
    ]

    operations = [
        migrations.AlterField(
            model_name='own',
            name='owner',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ФИО владельца'),
        ),
    ]
