# Generated by Django 2.2.24 on 2024-01-12 16:28

from django.db import migrations


def create_owner_in_own_model(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Own = apps.get_model('property', 'Own')
    flat_set = Flat.objects.all()
    for flat in flat_set.iterator():
        obj, _ = Own.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone,
        )
        obj.flat.set([flat])
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20240112_1926'),
    ]

    operations = [
        migrations.RunPython(create_owner_in_own_model)
    ]
