# Generated by Django 2.2.24 on 2024-01-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20240117_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='flat',
            new_name='flats',
        ),
    ]
