# Generated by Django 2.2.24 on 2024-01-27 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_auto_20240117_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='owner_pure_phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='processed_phone_number',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to=settings.AUTH_USER_MODEL, verbose_name='Кто жаловался'),
        ),
    ]
